### ISSUE TITLE
<p> html tags are not properly being placed

### ISSUE THREAD

**Issue by orbitaldecay** [civboot/cxt#2]
When cxt is converted to HTML by cxt.py, `<p>` tags are not being placed properly.

The cxt file:
```
This should be paragraph one.

This should be paragraph two.
```

Generates:
`<body>This should be paragraph one.<p>This should be paragraph two.</body>`

ER:
`<body><p>This should be paragraph one.</p><p>This should be paragraph two.</p></body>`

**Comment by vitiral** [comment]
Can you give an example?

**Comment by vitiral** [comment]
Ah I see. Does this cause issues in rendering? This was at least partially on purpose to simplify things a bit on the html encoding side.

**Comment by vitiral** [comment]
Ah nevermind, I see the difference

[new version](https://github.com/civboot/cxt/blob/d9b726ebde8ef735d7ecf9720216a1b9ee8c717d/README.md)

[old version](https://github.com/civboot/cxt)

The old version doesn't have line-spacing between some of the paragraphs. This was actually an annoyance I had before.

**Comment by orbitaldecay** [comment]
> Ah I see. Does this cause issues in rendering? This was at least partially on purpose to simplify things a bit on the html encoding side.

The first paragraph is rendered without a space between it and the second paragraph, so yeah. It does effect rendering in a way that I'm finding difficult.

**Comment by orbitaldecay** [comment]
> Ah nevermind, I see the difference
> 
> [new version](https://github.com/civboot/cxt/blob/d9b726ebde8ef735d7ecf9720216a1b9ee8c717d/README.md)
> 
> [old version](https://github.com/civboot/cxt)
> 
> The old version doesn't have line-spacing between some of the paragraphs. This was actually an annoyance I had before.

Exactly.

**Comment by orbitaldecay** [comment]
Testing now.

**Comment by orbitaldecay** [comment]
Looks good. Want to push to main?

**Comment by vitiral** [comment]
At some point I'd like to get better tests. This literally broke no tests, haha
